server:
  port: 18650

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: HardcoreyoyoGateWay-ServiceRBAC
          uri: lb://ServiceRBAC
#           uri: https://www.google.com.tw/
          predicates:
            - Path=/
