server:
  port: 18650

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: HardcoreyoyoGateWay-ServiceRBAC
          uri: lb://ServiceRBAC
          predicates:
            - Path=/
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin1234

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream
        
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5
        errorThresholdPercentage: 5
        sleepWindowInMilliseconds: 60000
        
github:
  test: 2022/0404/1245 for github test
