server:
  port: 18650

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: HardcoreyoyoGateWay-ServiceRBAC
          uri: lb://ServiceRBAC
          predicates:
            - Path=/
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin1234

management:
  endpoints:
    web:
      exposure:
        include: refresh,health
        
github:
  test: 2022/0404/1245 for github test
