server:
  port: 8401

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin1234

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/eureka/

feign:
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

github:
  test: 2022/0404/0036 for github test
