server:
 port: 8080

spring:
 application:
   name: Service-SMS
 cloud:
   nacos:
     discovery:
       server-addr: localhost:8848

feign:
 okhttp:
   enabled: true



#spring:
#  application:
#    name: Service-SMS
#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos:8848
#        port: ${DISCOVERY_PORT}
#      config:
#        server-addr: nacos:8848
#        file-extension: yaml
#        group: HARDCOREYOYO_GROUP
