server:
  port: 8402

spring:
  rabbitmq:
    host: mq
    port: 5672
    username: root
    password: admin1234

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/eureka/

feign:
  okhttp:
    enabled: true
#   hystrix:
#     enabled: true
    


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream

github:
  test: 2022/0404/0049 for github test

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5
        errorThresholdPercentage: 5
        sleepWindowInMilliseconds: 60000
