server:
  port: 8402

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin1234

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/eureka/

feign:
  okhttp:
    enabled: true

github:
  test: 2022/0404/0049 for github test
