server:
  port: 8401

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin1234

ribbon:
  eager-load:
    enabled: true
    clients: ServiceSMS

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/eureka/

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream

github:
  test: 2022/0404/0049 for github test

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5
        errorThresholdPercentage: 5
        sleepWindowInMilliseconds: 60000
